name: sync-labels
on:
  push:
    branches:
      - master
    paths:
      - .github/labels.yml
jobs:
  sync-labels:
    name: sync-labels
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: Brightspace/third-party-actions@actions/checkout
      - name: Sync labels
        uses: Brightspace/third-party-actions@micnncim/action-label-syncer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manifest: .github/labels.yml
